import { supabase } from "./supabase";


export type Card = {
  name: string;
  cost: number;
  count: number;
  card_id?: string;
};

export type Deck = {
  id: number;
  title: string;
  title_en: string;
  slug: string;
  hero_class: string;
  archetype: string;
  deck_code: string;
  dust_cost: number;
  tier: number;
  win_rate: number;
  guide: string;
  card_list: Card[];
  matchups: Record<string, number>;
  published_at: string;
  created_at: string;
};

const DEMO_DECKS: Deck[] = [
  {
    id: 1, title: "痛苦动物园", title_en: "Pain Zoo Warlock", slug: "pain-zoo-warlock",
    hero_class: "warlock", archetype: "aggro", deck_code: "AAECAf0GBseyBZXkBfH0Bf2ABvWeBu6rBgziyQT62wTb3QT03gTK8gT09QTF9gTx+AW7jAbJkAaHnAaInAYA",
    dust_cost: 6800, tier: 1, win_rate: 56.8,
    guide: "## 卡组思路\n\n利用自伤效果触发大量增益，快速铺场压制对手。前期用低费随从和自伤牌建立场面优势，中期通过波珈尔等强力卡牌收割。\n\n## 留牌策略\n\n- 火焰小鬼、虚空行者等1费随从必留\n- 渐强对快攻对局留\n- 灵魂撕裂对抗铺场留\n\n## 关键回合\n\n- **1-2费**：铺低费随从，利用自伤触发效果\n- **3-4费**：暗影烈焰或纳斯雷兹姆之触稳场\n- **5费**：波珈尔终结",
    card_list: [
      { name: "火焰小鬼", cost: 1, count: 2, card_id: "EX1_319" },
      { name: "虚空行者", cost: 1, count: 2, card_id: "CS2_065" },
      { name: "棘鳞魔蝎", cost: 1, count: 2, card_id: "WW_045" },
      { name: "渐强", cost: 2, count: 2, card_id: "TOY_517" },
      { name: "灵魂撕裂", cost: 2, count: 2, card_id: "GIL_614" },
      { name: "注入不朽", cost: 2, count: 2, card_id: "WW_046" },
      { name: "石腭怪宝石投手", cost: 3, count: 2, card_id: "WW_047" },
      { name: "纳斯雷兹姆之触", cost: 3, count: 2, card_id: "MAW_015" },
      { name: "深暗行者", cost: 3, count: 2, card_id: "TOY_518" },
      { name: "暗影烈焰", cost: 4, count: 2, card_id: "EX1_303" },
      { name: "恶魔打击", cost: 4, count: 2, card_id: "WW_048" },
      { name: "深渊呐喊", cost: 5, count: 2, card_id: "TOY_519" },
      { name: "吞噬灵魂", cost: 6, count: 2, card_id: "EX1_309" },
      { name: "扭曲虚空", cost: 8, count: 2, card_id: "EX1_312" },
      { name: "波珈尔", cost: 5, count: 1, card_id: "WW_052" },
      { name: "萨格拉斯", cost: 9, count: 1, card_id: "TTN_840" },
    ],
    matchups: { warrior: 58, mage: 52, hunter: 48, paladin: 55, priest: 62, rogue: 50, shaman: 54, warlock: 50, druid: 56, "demon-hunter": 53, "death-knight": 51 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 2, title: "海盗快攻死骑", title_en: "Pirate Aggro Death Knight", slug: "pirate-aggro-dk",
    hero_class: "death-knight", archetype: "aggro", deck_code: "AAECAdMKBu21BNi8BIO+BIzFBLjSBMLcBAzz0ASJ1ATi4wTV6gSO8QTf9ATd9wSu+gT3jQXDkQXFkQXBngUA",
    dust_cost: 5200, tier: 1, win_rate: 55.4,
    guide: "## 卡组思路\n\n利用海盗随从快速铺场，配合死亡骑士的符文能力打出爆发伤害。前期抢节奏，中期用武器和直伤收割。\n\n## 留牌策略\n\n- 所有1费海盗必留\n- 冰霜打击对快攻留\n- 亡者之镰对慢速对局留\n\n## 关键回合\n\n- **1-2费**：海盗铺场\n- **3费**：天灾斧配合海盗\n- **5-6费**：持续压血线，寻找斩杀",
    card_list: [
      { name: "霍克斯特莱德骑手", cost: 1, count: 2, card_id: "WW_321" },
      { name: "瘟疫谷物", cost: 1, count: 2, card_id: "MAW_002" },
      { name: "亡者之镰", cost: 1, count: 2, card_id: "MAW_003" },
      { name: "冰霜打击", cost: 2, count: 2, card_id: "CORE_RLK_223" },
      { name: "海盗甲板水手", cost: 2, count: 2, card_id: "WW_322" },
      { name: "血色水手", cost: 2, count: 2, card_id: "WW_323" },
      { name: "骨髓操控者", cost: 3, count: 2, card_id: "MAW_006" },
      { name: "天灾斧", cost: 3, count: 2, card_id: "WW_324" },
      { name: "自作自受", cost: 3, count: 2, card_id: "MAW_007" },
      { name: "尸骸追踪者", cost: 4, count: 2, card_id: "WW_325" },
      { name: "亡者收割", cost: 4, count: 2, card_id: "MAW_009" },
      { name: "幽灵海盗", cost: 5, count: 2, card_id: "WW_326" },
      { name: "黑暗意志", cost: 5, count: 2, card_id: "MAW_010" },
      { name: "恐怖盛宴", cost: 6, count: 2, card_id: "MAW_011" },
      { name: "莫格莱尼", cost: 7, count: 1, card_id: "MAW_012" },
      { name: "巫妖王", cost: 10, count: 1, card_id: "MAW_013" },
    ],
    matchups: { warrior: 56, mage: 55, hunter: 52, paladin: 58, priest: 60, rogue: 48, shaman: 53, warlock: 50, druid: 54, "demon-hunter": 51, "death-knight": 50 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 3, title: "挖掘贼", title_en: "Excavate Rogue", slug: "excavate-rogue",
    hero_class: "rogue", archetype: "combo", deck_code: "AAECAaIHBLPhBOHtBNj0BLCDBQTu4wS+7QSs8AS18QT/9gSsgAWvgAWFgwUA",
    dust_cost: 9600, tier: 1, win_rate: 56.2,
    guide: "## 卡组思路\n\n通过挖掘机制生成大量宝藏和资源，配合弹回和减费实现高效combo。中期积攒资源，后期一波爆发。\n\n## 留牌策略\n\n- 背刺、预谋必留\n- 挖掘发现对所有对局留\n- 致命药膏对快攻留\n\n## 关键回合\n\n- **0-2费**：背刺控场，挖掘积累\n- **3-4费**：索尼娅配合暗影步循环\n- **5-6费**：挖掘宝库获取终极宝藏",
    card_list: [
      { name: "背刺", cost: 0, count: 2, card_id: "CS2_072" },
      { name: "预谋", cost: 0, count: 2, card_id: "EX1_145" },
      { name: "暗影步", cost: 0, count: 2, card_id: "EX1_144" },
      { name: "致命药膏", cost: 1, count: 2, card_id: "CS2_074" },
      { name: "迅捷药膏", cost: 1, count: 2, card_id: "TOY_508" },
      { name: "挖掘发现", cost: 2, count: 2, card_id: "WW_412" },
      { name: "地底探险", cost: 2, count: 2, card_id: "WW_413" },
      { name: "军情七处特工", cost: 3, count: 2, card_id: "EX1_134" },
      { name: "暗影之牙", cost: 3, count: 2, card_id: "TOY_509" },
      { name: "猩红绽放", cost: 4, count: 2, card_id: "WW_414" },
      { name: "骨刺暗杀者", cost: 5, count: 2, card_id: "TOY_510" },
      { name: "挖掘宝库", cost: 5, count: 2, card_id: "WW_415" },
      { name: "消失", cost: 6, count: 2, card_id: "EX1_128" },
      { name: "影舞者索尼娅", cost: 3, count: 1, card_id: "WW_416" },
      { name: "小德里利", cost: 4, count: 1, card_id: "WW_417" },
      { name: "托奇", cost: 2, count: 1, card_id: "TOY_511" },
      { name: "吉利克斯", cost: 5, count: 1, card_id: "TOY_330" },
    ],
    matchups: { warrior: 55, mage: 58, hunter: 50, paladin: 54, priest: 57, rogue: 50, shaman: 52, warlock: 56, druid: 53, "demon-hunter": 54, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 4, title: "巨龙德鲁伊", title_en: "Dragon Druid", slug: "dragon-druid",
    hero_class: "druid", archetype: "midrange", deck_code: "AAECAZICBrWYBfCbBYelBYKuBe60Be+0BQzA7gS68ASf8QTs9QSK+AWs+AWU+gXIgAaDigaYjAbNmgbvnAYA",
    dust_cost: 10400, tier: 1, win_rate: 55.8,
    guide: "## 卡组思路\n\n通过跳费快速拉到高费，释放强力巨龙统治场面。中期龙群压制，后期伊瑟拉和阿莱克斯塔萨终结。\n\n## 留牌策略\n\n- 激活、野性成长必留\n- 嬉水幼龙对所有对局留\n- 横扫对快攻留\n\n## 关键回合\n\n- **1-2费**：激活跳费或野性成长\n- **4-5费**：龙巢守卫稳场\n- **7-9费**：巨龙压制终结",
    card_list: [
      { name: "激活", cost: 0, count: 2, card_id: "EX1_169" },
      { name: "野性成长", cost: 2, count: 2, card_id: "CS2_013" },
      { name: "嬉水幼龙", cost: 2, count: 2, card_id: "WW_801" },
      { name: "龙巢之卵", cost: 2, count: 2, card_id: "WW_802" },
      { name: "滋养", cost: 3, count: 2, card_id: "EX1_164" },
      { name: "翡翠幼龙", cost: 3, count: 2, card_id: "WW_803" },
      { name: "龙息术", cost: 3, count: 2, card_id: "TOY_801" },
      { name: "横扫", cost: 4, count: 2, card_id: "CS2_012" },
      { name: "龙巢守卫", cost: 4, count: 2, card_id: "WW_804" },
      { name: "星界飞龙", cost: 5, count: 2, card_id: "TOY_802" },
      { name: "翡翠巨龙", cost: 7, count: 2, card_id: "WW_805" },
      { name: "龙之女王", cost: 8, count: 2, card_id: "TOY_803" },
      { name: "终极感染", cost: 10, count: 2, card_id: "ICC_047" },
      { name: "暮阳菲叶", cost: 6, count: 1, card_id: "WW_806" },
      { name: "伊瑟拉", cost: 9, count: 1, card_id: "EX1_572" },
      { name: "阿莱克斯塔萨", cost: 9, count: 1, card_id: "EX1_561" },
      { name: "吉利克斯三千型", cost: 5, count: 1, card_id: "TOY_330" },
    ],
    matchups: { warrior: 60, mage: 55, hunter: 48, paladin: 54, priest: 58, rogue: 50, shaman: 56, warlock: 52, druid: 50, "demon-hunter": 53, "death-knight": 55 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 5, title: "手牌骑", title_en: "Handbuff Paladin", slug: "handbuff-paladin",
    hero_class: "paladin", archetype: "midrange", deck_code: "AAECAZ8FBv2fBZKjBcOtBcu0Bba8BdLPBQzf7QTh8AT48gT49QTI9wTW+QSKgAW3gAXYlwaYnAbTnAbengYA",
    dust_cost: 6400, tier: 1, win_rate: 55.2,
    guide: "## 卡组思路\n\n在手中持续buff随从，打出高质量大身材生物。圣光灌注者和肌肉机器人是核心引擎，配合各种手牌增益效果制造巨大威胁。\n\n## 留牌策略\n\n- 正义保卫者、自动防御矩阵必留\n- 阿达尔之手对所有对局留\n- 王国骑士对慢速对局留\n\n## 关键回合\n\n- **1-2费**：铺低费随从\n- **3费**：圣光灌注者开始buff\n- **4-5费**：打出被buff的大身材随从",
    card_list: [
      { name: "正义保卫者", cost: 1, count: 2, card_id: "ICC_038" },
      { name: "自动防御矩阵", cost: 1, count: 2, card_id: "TOY_380" },
      { name: "阿达尔之手", cost: 2, count: 2, card_id: "BT_011" },
      { name: "秘焰明镜", cost: 2, count: 2, card_id: "TOY_381" },
      { name: "气泡枪手", cost: 2, count: 2, card_id: "WW_381" },
      { name: "肌肉机器人", cost: 3, count: 2, card_id: "TOY_382" },
      { name: "圣光灌注者", cost: 3, count: 2, card_id: "WW_382" },
      { name: "王国骑士", cost: 3, count: 2, card_id: "WW_383" },
      { name: "连击冲锋", cost: 4, count: 2, card_id: "TOY_383" },
      { name: "圣光审判", cost: 4, count: 2, card_id: "WW_384" },
      { name: "神圣裁决", cost: 5, count: 2, card_id: "TOY_384" },
      { name: "光铸巨像", cost: 5, count: 2, card_id: "WW_385" },
      { name: "联盟先锋", cost: 6, count: 2, card_id: "WW_386" },
      { name: "光铸勇士", cost: 7, count: 2, card_id: "TOY_385" },
      { name: "提里奥·弗丁", cost: 8, count: 1, card_id: "EX1_383" },
      { name: "琳妮萨·夕阳之悲", cost: 7, count: 1, card_id: "LOOT_216" },
    ],
    matchups: { warrior: 56, mage: 53, hunter: 50, paladin: 50, priest: 55, rogue: 48, shaman: 57, warlock: 52, druid: 54, "demon-hunter": 56, "death-knight": 53 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 6, title: "龙牧", title_en: "Zarimi Dragon Priest", slug: "zarimi-dragon-priest",
    hero_class: "priest", archetype: "midrange", deck_code: "AAECAa0GBtfvBKT5BO6ABbuNBb6WBdKeBgzo5ATc5gTw8QS09ASJ+ASl+gT2gAXEhAWQhgWvjAX7kQX3nQYA",
    dust_cost: 8800, tier: 1, win_rate: 56.0,
    guide: "## 卡组思路\n\n以龙族随从为核心，通过扎利米实现强力节奏输出。龙族协同效果叠加，中期打出碾压性场面优势。\n\n## 留牌策略\n\n- 暮光幼龙、龙鳞学徒必留\n- 真言术:盾对所有对局留\n- 清场法术对快攻留\n\n## 关键回合\n\n- **1-2费**：龙族随从铺场\n- **3-4费**：龙族协同触发\n- **5费**：扎利米终结攻势",
    card_list: [
      { name: "真言术:盾", cost: 0, count: 2, card_id: "CS2_004" },
      { name: "圣洁之光", cost: 1, count: 2, card_id: "CS1_130" },
      { name: "暮光幼龙", cost: 1, count: 2, card_id: "WW_901" },
      { name: "龙鳞学徒", cost: 2, count: 2, card_id: "TOY_901" },
      { name: "狂乱", cost: 2, count: 2, card_id: "WW_902" },
      { name: "圣光弹幕", cost: 2, count: 2, card_id: "TOY_902" },
      { name: "龙之怒", cost: 3, count: 2, card_id: "WW_903" },
      { name: "深渊龙人", cost: 3, count: 2, card_id: "TOY_903" },
      { name: "暗言术:灭", cost: 3, count: 2, card_id: "EX1_622" },
      { name: "龙眠执行者", cost: 4, count: 2, card_id: "WW_904" },
      { name: "光耀之翼", cost: 5, count: 2, card_id: "TOY_904" },
      { name: "圣光龙息", cost: 5, count: 2, card_id: "WW_905" },
      { name: "龙族先知", cost: 6, count: 2, card_id: "WW_906" },
      { name: "扎利米", cost: 5, count: 1, card_id: "VAC_921" },
      { name: "穆罗兹翁德", cost: 8, count: 1, card_id: "WW_907" },
      { name: "灵魂行者安都因", cost: 7, count: 1, card_id: "TOY_905" },
      { name: "拉兹", cost: 4, count: 1, card_id: "WW_908" },
    ],
    matchups: { warrior: 58, mage: 54, hunter: 52, paladin: 53, priest: 50, rogue: 52, shaman: 55, warlock: 54, druid: 56, "demon-hunter": 58, "death-knight": 55 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 7, title: "快攻猎", title_en: "Face Hunter", slug: "face-hunter",
    hero_class: "hunter", archetype: "aggro", deck_code: "AAECAR8C6aUD5e4DDogK/gz4sQLbsgK1A4cEyQTJBLUDmAKoArUDhwSXBMkE",
    dust_cost: 4200, tier: 1, win_rate: 55.6,
    guide: "## 卡组思路\n\n纯粹的快攻策略，所有资源都用来打脸。低费随从配合直伤法术，争取在6-7回合结束比赛。\n\n## 留牌策略\n\n- 所有1费随从必留\n- 奥术射击必留\n- 快速射击对慢速对局留\n\n## 关键回合\n\n- **1-3费**：全力铺场打脸\n- **4-5费**：直伤法术收人头\n- **6-7费**：英雄技能+法术斩杀",
    card_list: [
      { name: "奥术射击", cost: 1, count: 2, card_id: "DS1_185" },
      { name: "追踪术", cost: 1, count: 2, card_id: "DS1_184" },
      { name: "热切的食腐土狼", cost: 1, count: 2, card_id: "WW_028" },
      { name: "爆裂射击", cost: 1, count: 2, card_id: "TOY_028" },
      { name: "快速射击", cost: 2, count: 2, card_id: "BRM_013" },
      { name: "弹射之网", cost: 2, count: 2, card_id: "WW_029" },
      { name: "炸弹猎手", cost: 2, count: 2, card_id: "TOY_029" },
      { name: "动物伙伴", cost: 3, count: 2, card_id: "NEW1_031" },
      { name: "杀戮命令", cost: 3, count: 2, card_id: "EX1_539" },
      { name: "鹰角弓", cost: 3, count: 2, card_id: "EX1_536" },
      { name: "冰冻陷阱", cost: 2, count: 2, card_id: "EX1_611" },
      { name: "爆炸陷阱", cost: 2, count: 2, card_id: "EX1_610" },
      { name: "多头蛇", cost: 4, count: 2, card_id: "UNG_919" },
      { name: "怒火中烧", cost: 5, count: 2, card_id: "WW_030" },
      { name: "洛卡拉", cost: 3, count: 1, card_id: "WW_031" },
      { name: "希尔瓦娜斯·风行者", cost: 6, count: 1, card_id: "EX1_016" },
    ],
    matchups: { warrior: 48, mage: 55, hunter: 50, paladin: 52, priest: 58, rogue: 53, shaman: 50, warlock: 56, druid: 58, "demon-hunter": 52, "death-knight": 54 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 8, title: "彩虹法师", title_en: "Rainbow Mage", slug: "rainbow-mage",
    hero_class: "mage", archetype: "combo", deck_code: "AAECAf0EBuWwBYa1BYa3Bc27Bde9BYLCBQzl0ASJ1ATi4wTV6gSO8QTf9ATd9wSu+gT3jQXDkQXFkQXBngUA",
    dust_cost: 11200, tier: 2, win_rate: 53.4,
    guide: "## 卡组思路\n\n收集所有法术学派的法术来触发彩虹效果。通过高效法术控场，最终用希芙配合多学派法术一波斩杀。\n\n## 留牌策略\n\n- 奥术智慧、寒冰箭必留\n- 法力饼干对所有对局留\n- 灭世射线对快攻留\n\n## 关键回合\n\n- **2-3费**：过牌积攒法术\n- **4-5费**：控场收集学派\n- **7费**：希芙爆发斩杀",
    card_list: [
      { name: "法力饼干", cost: 0, count: 2, card_id: "TOY_508" },
      { name: "奥术飞弹", cost: 1, count: 2, card_id: "EX1_277" },
      { name: "发现学派", cost: 1, count: 2, card_id: "TOY_601" },
      { name: "寒冰箭", cost: 2, count: 2, card_id: "CS2_024" },
      { name: "奥术智慧", cost: 3, count: 2, card_id: "CS2_023" },
      { name: "灭世射线", cost: 3, count: 2, card_id: "TOY_602" },
      { name: "虚空裂隙", cost: 3, count: 2, card_id: "WW_601" },
      { name: "火球术", cost: 4, count: 2, card_id: "CS2_029" },
      { name: "聚合打击", cost: 4, count: 2, card_id: "TOY_603" },
      { name: "烈焰风暴", cost: 7, count: 2, card_id: "CS2_032" },
      { name: "焰流涌动", cost: 5, count: 2, card_id: "WW_602" },
      { name: "彩虹光辉", cost: 6, count: 2, card_id: "TOY_604" },
      { name: "希芙", cost: 7, count: 1, card_id: "TTN_960" },
      { name: "星术师索拉利安", cost: 2, count: 1, card_id: "BT_028" },
      { name: "约格-萨隆", cost: 10, count: 1, card_id: "TTN_841" },
      { name: "大法师安东尼达斯", cost: 7, count: 1, card_id: "EX1_559" },
      { name: "伊格尼斯", cost: 4, count: 1, card_id: "TTN_429" },
      { name: "彩虹画师", cost: 3, count: 1, card_id: "TOY_605" },
    ],
    matchups: { warrior: 48, mage: 50, hunter: 46, paladin: 55, priest: 58, rogue: 50, shaman: 52, warlock: 54, druid: 56, "demon-hunter": 48, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 9, title: "自然萨满", title_en: "Nature Shaman", slug: "nature-shaman",
    hero_class: "shaman", archetype: "combo", deck_code: "AAECAaoIBJzOA7HSBKP3BN65BQ275gOS5wP26AO47AOq7gOm7wPB9AOZ+QP",
    dust_cost: 7600, tier: 2, win_rate: 54.2,
    guide: "## 卡组思路\n\n利用自然法术叠加法术伤害，配合闪电箭和闪电风暴控场，最终用自然之力打出大量爆发伤害。\n\n## 留牌策略\n\n- 闪电箭、图腾雕纹必留\n- 法力潮涌图腾对所有对局留\n- 闪电风暴对快攻留\n\n## 关键回合\n\n- **1-2费**：法力潮涌和图腾积累\n- **3-4费**：法术控场积攒\n- **5-7费**：自然爆发终结",
    card_list: [
      { name: "闪电箭", cost: 1, count: 2, card_id: "EX1_238" },
      { name: "图腾雕纹", cost: 1, count: 2, card_id: "WW_701" },
      { name: "法力潮涌图腾", cost: 1, count: 2, card_id: "TOY_701" },
      { name: "荒野低语", cost: 2, count: 2, card_id: "WW_702" },
      { name: "熔岩爆裂", cost: 2, count: 2, card_id: "EX1_241" },
      { name: "自然之刃", cost: 2, count: 2, card_id: "TOY_702" },
      { name: "闪电风暴", cost: 3, count: 2, card_id: "EX1_259" },
      { name: "自然引导", cost: 3, count: 2, card_id: "WW_703" },
      { name: "大地震击", cost: 3, count: 2, card_id: "TOY_703" },
      { name: "妖术", cost: 4, count: 2, card_id: "EX1_246" },
      { name: "拟态荚", cost: 4, count: 2, card_id: "WW_704" },
      { name: "嗜血", cost: 5, count: 2, card_id: "CS2_046" },
      { name: "旋风之力", cost: 5, count: 2, card_id: "TOY_704" },
      { name: "巨人猎手泰丽莎", cost: 6, count: 1, card_id: "WW_705" },
      { name: "震颤方块", cost: 4, count: 1, card_id: "WW_706" },
      { name: "布鲁坎", cost: 8, count: 1, card_id: "AV_258" },
      { name: "阿曼瑟尔", cost: 10, count: 1, card_id: "TTN_842" },
    ],
    matchups: { warrior: 56, mage: 52, hunter: 48, paladin: 53, priest: 55, rogue: 50, shaman: 50, warlock: 52, druid: 54, "demon-hunter": 51, "death-knight": 53 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 10, title: "纳迦恶魔猎手", title_en: "Naga Demon Hunter", slug: "naga-demon-hunter",
    hero_class: "demon-hunter", archetype: "aggro", deck_code: "AAECAea5AwTZ6QPj9QON9wPHsgQN2cYD3dMDieQDiuQDjOQDi+gD8+gDwvEDifcDyIAE1JIE",
    dust_cost: 5600, tier: 2, win_rate: 53.8,
    guide: "## 卡组思路\n\n利用纳迦族随从快速铺场，配合恶魔猎手的爆发能力打出致命伤害。低费纳迦配合法术形成强力节奏。\n\n## 留牌策略\n\n- 所有1费纳迦必留\n- 二段跳必留\n- 魔能弹幕对快攻留\n\n## 关键回合\n\n- **1-2费**：纳迦铺场\n- **3费**：恶魔之翼配合法术\n- **4-5费**：爆发打脸收割",
    card_list: [
      { name: "二段跳", cost: 1, count: 2, card_id: "TOY_400" },
      { name: "纳迦先锋", cost: 1, count: 2, card_id: "TSC_057" },
      { name: "魔能弹幕", cost: 1, count: 2, card_id: "WW_401" },
      { name: "潮汐浪涌者", cost: 1, count: 2, card_id: "TOY_401" },
      { name: "邪能学徒", cost: 2, count: 2, card_id: "WW_402" },
      { name: "混沌打击", cost: 2, count: 2, card_id: "BT_235" },
      { name: "纳迦吟游者", cost: 2, count: 2, card_id: "TOY_402" },
      { name: "多鳍刺客", cost: 3, count: 2, card_id: "WW_403" },
      { name: "战刃吉他", cost: 3, count: 2, card_id: "ETC_080" },
      { name: "恶魔之翼", cost: 3, count: 2, card_id: "TOY_403" },
      { name: "深渊纳迦", cost: 4, count: 2, card_id: "WW_404" },
      { name: "邪能突袭", cost: 4, count: 2, card_id: "TOY_404" },
      { name: "怒鳞纳迦", cost: 5, count: 2, card_id: "WW_405" },
      { name: "末日守卫", cost: 5, count: 2, card_id: "TOY_405" },
      { name: "伊利达雷之怒", cost: 6, count: 1, card_id: "WW_406" },
      { name: "卡尔萨斯·逐日者", cost: 7, count: 1, card_id: "WW_407" },
    ],
    matchups: { warrior: 54, mage: 56, hunter: 52, paladin: 50, priest: 55, rogue: 48, shaman: 52, warlock: 50, druid: 53, "demon-hunter": 50, "death-knight": 54 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 11, title: "雷诺战士", title_en: "Reno Control Warrior", slug: "reno-control-warrior",
    hero_class: "warrior", archetype: "control", deck_code: "AAECAQcesAKRA40OkBCFF5AX+wyBDp8O0RGiEJMQjhD+FOMW4hfyFdYRyRG5E7kW8BftFf4WkBeME/oW",
    dust_cost: 14800, tier: 2, win_rate: 53.2,
    guide: "## 卡组思路\n\n雷诺高地战士，所有卡牌各一张。通过强力解场和大量护甲苟活到后期，雷诺清场后反击取胜。\n\n## 留牌策略\n\n- 盾牌格挡、乱斗必留\n- 斩杀对大随从对局留\n- 盾牌猛击对所有对局留\n\n## 关键回合\n\n- **1-3费**：积攒护甲\n- **5费**：乱斗清场\n- **9费**：雷诺一键翻盘",
    card_list: [
      { name: "斩杀", cost: 1, count: 1, card_id: "CS2_108" },
      { name: "盾牌猛击", cost: 1, count: 1, card_id: "EX1_410" },
      { name: "锐利之刃", cost: 1, count: 1, card_id: "WW_340" },
      { name: "猛击", cost: 2, count: 1, card_id: "WW_341" },
      { name: "铸甲师", cost: 2, count: 1, card_id: "EX1_402" },
      { name: "残忍打击", cost: 2, count: 1, card_id: "TOY_340" },
      { name: "盾牌格挡", cost: 3, count: 1, card_id: "EX1_606" },
      { name: "猛烈打击", cost: 3, count: 1, card_id: "WW_342" },
      { name: "重锤猛击", cost: 3, count: 1, card_id: "TOY_341" },
      { name: "血吼", cost: 4, count: 1, card_id: "CS2_112" },
      { name: "火车王里诺艾", cost: 4, count: 1, card_id: "WW_343" },
      { name: "严阵以待", cost: 4, count: 1, card_id: "TOY_342" },
      { name: "乱斗", cost: 5, count: 1, card_id: "EX1_407" },
      { name: "勇敢的水手", cost: 5, count: 1, card_id: "WW_344" },
      { name: "试炼", cost: 5, count: 1, card_id: "TOY_343" },
      { name: "破城者", cost: 6, count: 1, card_id: "WW_345" },
      { name: "砰砰博士", cost: 7, count: 1, card_id: "GVG_110" },
      { name: "旋风斩大师", cost: 6, count: 1, card_id: "TOY_344" },
      { name: "格罗玛什·地狱咆哮", cost: 8, count: 1, card_id: "EX1_414" },
      { name: "奥丁", cost: 8, count: 1, card_id: "TTN_960" },
      { name: "雷诺·杰克逊", cost: 9, count: 1, card_id: "WW_0700" },
      { name: "布莱恩·铜须", cost: 6, count: 1, card_id: "WW_0800" },
      { name: "吉利克斯三千型", cost: 5, count: 1, card_id: "TOY_330" },
      { name: "伊格尼斯", cost: 4, count: 1, card_id: "TTN_429" },
      { name: "伊利斯·逐星", cost: 4, count: 1, card_id: "WW_0900" },
      { name: "芬利爵士", cost: 1, count: 1, card_id: "WW_0901" },
      { name: "约格-萨隆", cost: 10, count: 1, card_id: "TTN_841" },
      { name: "亚煞极", cost: 7, count: 1, card_id: "WW_346" },
      { name: "巨盾卫士", cost: 7, count: 1, card_id: "TOY_345" },
      { name: "佐拉", cost: 3, count: 1, card_id: "LOOT_516" },
    ],
    matchups: { warrior: 50, mage: 52, hunter: 48, paladin: 55, priest: 56, rogue: 50, shaman: 53, warlock: 54, druid: 52, "demon-hunter": 55, "death-knight": 50 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 12, title: "奇迹贼", title_en: "Miracle Rogue", slug: "miracle-rogue",
    hero_class: "rogue", archetype: "combo", deck_code: "AAECAaIHBK+RA68QhBfprgMNtAHtAs0DiAXUBYgH3Qjr8AKPlwOQlwO3nwPA",
    dust_cost: 8400, tier: 2, win_rate: 52.8,
    guide: "## 卡组思路\n\n通过大量低费法术触发连击效果和加基森拍卖师过牌，积攒伤害后配合暗影步循环打出斩杀。\n\n## 留牌策略\n\n- 背刺、预谋、暗影步必留\n- 加基森拍卖师对慢速留\n- 致命药膏对快攻留\n\n## 关键回合\n\n- **0-2费**：控场积攒连击\n- **4-5费**：加基森过牌引擎启动\n- **6-7费**：暗影步循环完成斩杀",
    card_list: [
      { name: "背刺", cost: 0, count: 2, card_id: "CS2_072" },
      { name: "预谋", cost: 0, count: 2, card_id: "EX1_145" },
      { name: "暗影步", cost: 0, count: 2, card_id: "EX1_144" },
      { name: "致命药膏", cost: 1, count: 2, card_id: "CS2_074" },
      { name: "幽灵匕首", cost: 1, count: 2, card_id: "TOY_507" },
      { name: "闷棍", cost: 2, count: 2, card_id: "EX1_141" },
      { name: "刺骨", cost: 2, count: 2, card_id: "CS2_073" },
      { name: "疾跑", cost: 2, count: 2, card_id: "TOY_512" },
      { name: "暗影连击", cost: 3, count: 2, card_id: "WW_418" },
      { name: "刀扇", cost: 3, count: 2, card_id: "EX1_129" },
      { name: "加基森拍卖师", cost: 5, count: 2, card_id: "EX1_095" },
      { name: "幽暗城药剂师", cost: 5, count: 2, card_id: "WW_419" },
      { name: "暗影之舞", cost: 6, count: 2, card_id: "TOY_513" },
      { name: "影舞者索尼娅", cost: 3, count: 1, card_id: "WW_416" },
      { name: "艾德温·范克里夫", cost: 3, count: 1, card_id: "EX1_613" },
      { name: "维拉诺斯", cost: 4, count: 1, card_id: "TOY_514" },
      { name: "坦纳瑞丝·苦水", cost: 6, count: 1, card_id: "WW_420" },
    ],
    matchups: { warrior: 55, mage: 52, hunter: 46, paladin: 50, priest: 58, rogue: 50, shaman: 48, warlock: 54, druid: 52, "demon-hunter": 50, "death-knight": 53 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 13, title: "疯狂术士", title_en: "Insanity Warlock", slug: "insanity-warlock",
    hero_class: "warlock", archetype: "combo", deck_code: "AAECAf0GBp/OA5XeA9DhA87hA/bjA4P0Awzx0AOV3QPQ4QP14wOD9AOE9AOF9APD+QPJ+QP",
    dust_cost: 9200, tier: 2, win_rate: 53.0,
    guide: "## 卡组思路\n\n通过疯狂轮转和低费法术大量过牌，构建手牌组合拳。利用自伤机制触发增益效果，最终一波爆发斩杀。\n\n## 留牌策略\n\n- 生命分流必留\n- 虚空行者对快攻留\n- 灵魂撕裂对所有对局留\n\n## 关键回合\n\n- **1-3费**：过牌积累\n- **4-5费**：自伤触发效果\n- **7-8费**：疯狂爆发斩杀",
    card_list: [
      { name: "虚空行者", cost: 1, count: 2, card_id: "CS2_065" },
      { name: "牺牲契约", cost: 0, count: 2, card_id: "NEW1_003" },
      { name: "生命分流", cost: 1, count: 2, card_id: "CS2_059" },
      { name: "灵魂撕裂", cost: 2, count: 2, card_id: "GIL_614" },
      { name: "恶魔之火", cost: 2, count: 2, card_id: "EX1_596" },
      { name: "疯狂轮转", cost: 2, count: 2, card_id: "WW_049" },
      { name: "地狱烈焰", cost: 4, count: 2, card_id: "CS2_062" },
      { name: "恶魔变形术", cost: 3, count: 2, card_id: "WW_050" },
      { name: "深渊召唤者", cost: 3, count: 2, card_id: "TOY_520" },
      { name: "亡者复生", cost: 4, count: 2, card_id: "WW_051" },
      { name: "噩梦缠身", cost: 5, count: 2, card_id: "TOY_521" },
      { name: "深渊传送门", cost: 6, count: 2, card_id: "WW_053" },
      { name: "灵魂交换", cost: 7, count: 2, card_id: "TOY_522" },
      { name: "萨格拉斯", cost: 9, count: 1, card_id: "TTN_840" },
      { name: "塔姆辛·罗姆", cost: 4, count: 1, card_id: "AV_277" },
      { name: "拉法姆", cost: 7, count: 1, card_id: "WW_054" },
      { name: "基尔加丹", cost: 10, count: 1, card_id: "WW_055" },
    ],
    matchups: { warrior: 52, mage: 50, hunter: 46, paladin: 54, priest: 56, rogue: 48, shaman: 53, warlock: 50, druid: 55, "demon-hunter": 50, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 14, title: "奥秘猎", title_en: "Secret Hunter", slug: "secret-hunter",
    hero_class: "hunter", archetype: "midrange", deck_code: "AAECAR8Cx6sEyqsEDqK5A9zMA6LOA7nSA4biA5bjA5TkA/DsA8f5A7+ABMOABIWkBA==",
    dust_cost: 5800, tier: 2, win_rate: 53.6,
    guide: "## 卡组思路\n\n利用奥秘和奥秘协同卡打出节奏优势。中速策略，通过奥秘干扰对手节奏，配合强力随从完成击杀。\n\n## 留牌策略\n\n- 追踪术、奥术射击必留\n- 冰冻陷阱、爆炸陷阱必留\n- 动物伙伴对所有对局留\n\n## 关键回合\n\n- **1-2费**：奥秘铺场\n- **3-4费**：奥秘协同触发\n- **5-6费**：中期随从收割",
    card_list: [
      { name: "追踪术", cost: 1, count: 2, card_id: "DS1_184" },
      { name: "奥术射击", cost: 1, count: 2, card_id: "DS1_185" },
      { name: "爆炸陷阱", cost: 2, count: 2, card_id: "EX1_610" },
      { name: "冰冻陷阱", cost: 2, count: 2, card_id: "EX1_611" },
      { name: "蛇阱", cost: 2, count: 2, card_id: "EX1_554" },
      { name: "游荡怪物", cost: 2, count: 2, card_id: "WW_032" },
      { name: "鹰角弓", cost: 3, count: 2, card_id: "EX1_536" },
      { name: "动物伙伴", cost: 3, count: 2, card_id: "NEW1_031" },
      { name: "杀戮命令", cost: 3, count: 2, card_id: "EX1_539" },
      { name: "奥秘吞噬者", cost: 4, count: 2, card_id: "TOY_033" },
      { name: "多头蛇", cost: 4, count: 2, card_id: "UNG_919" },
      { name: "奥秘守护者", cost: 4, count: 2, card_id: "WW_033" },
      { name: "狮鹫骑手", cost: 5, count: 2, card_id: "TOY_034" },
      { name: "怒火中烧", cost: 5, count: 2, card_id: "WW_030" },
      { name: "洛卡拉", cost: 3, count: 1, card_id: "WW_031" },
      { name: "希尔瓦娜斯·风行者", cost: 6, count: 1, card_id: "EX1_016" },
    ],
    matchups: { warrior: 52, mage: 54, hunter: 50, paladin: 48, priest: 55, rogue: 52, shaman: 50, warlock: 54, druid: 56, "demon-hunter": 54, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 15, title: "快攻骑", title_en: "Aggro Paladin", slug: "aggro-paladin",
    hero_class: "paladin", archetype: "aggro", deck_code: "AAECAZ8FAtmuA+ewAw7FA60DrwOvBO0FuMcCrPcC+v4C44YDk50D",
    dust_cost: 4600, tier: 2, win_rate: 54.4,
    guide: "## 卡组思路\n\n快速铺场，利用buff法术和圣骑士英雄技能不断制造威胁。前期随从铺场，中期buff爆发。\n\n## 留牌策略\n\n- 所有1费随从必留\n- 阿达尔之手必留\n- 力量祝福对慢速对局留\n\n## 关键回合\n\n- **1-2费**：全力铺场\n- **3费**：buff随从交换\n- **4-5费**：冲锋或buff斩杀",
    card_list: [
      { name: "正义保卫者", cost: 1, count: 2, card_id: "ICC_038" },
      { name: "圣盾骑兵", cost: 1, count: 2, card_id: "WW_387" },
      { name: "力量祝福", cost: 1, count: 2, card_id: "CS2_087" },
      { name: "阿达尔之手", cost: 2, count: 2, card_id: "BT_011" },
      { name: "闪光之剑", cost: 2, count: 2, card_id: "TOY_386" },
      { name: "圣光使者", cost: 2, count: 2, card_id: "WW_388" },
      { name: "剑龙骑术", cost: 3, count: 2, card_id: "UNG_950" },
      { name: "联盟旗手", cost: 3, count: 2, card_id: "TOY_387" },
      { name: "冲锋圣骑", cost: 3, count: 2, card_id: "WW_389" },
      { name: "圣光之翼", cost: 4, count: 2, card_id: "TOY_388" },
      { name: "奉献", cost: 4, count: 2, card_id: "CS2_093" },
      { name: "神恩术", cost: 4, count: 2, card_id: "WW_390" },
      { name: "连击突袭", cost: 5, count: 2, card_id: "TOY_389" },
      { name: "光耀斩杀", cost: 5, count: 2, card_id: "WW_391" },
      { name: "莱拉·暗月", cost: 4, count: 1, card_id: "TOY_390" },
      { name: "战旗统帅", cost: 6, count: 1, card_id: "WW_392" },
    ],
    matchups: { warrior: 50, mage: 55, hunter: 52, paladin: 50, priest: 56, rogue: 48, shaman: 54, warlock: 52, druid: 55, "demon-hunter": 53, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 16, title: "大法术法师", title_en: "Big Spell Mage", slug: "big-spell-mage",
    hero_class: "mage", archetype: "control", deck_code: "AAECAf0EBsW4A5LLA4XNA8fOA9DOA/fRA+DRA9nRA97RA4PhA/rhAwA=",
    dust_cost: 12600, tier: 2, win_rate: 52.6,
    guide: "## 卡组思路\n\n只带高费法术，配合减费效果提前释放毁灭性法术。前期用冰冻苟命，中后期大法术碾压对手。\n\n## 留牌策略\n\n- 寒冰箭必留\n- 奥术智慧必留\n- 法术减费卡对所有对局留\n\n## 关键回合\n\n- **2-3费**：寒冰箭控场\n- **4-5费**：减费引擎启动\n- **6-8费**：大法术清场统治",
    card_list: [
      { name: "法力饼干", cost: 0, count: 2, card_id: "SCH_509" },
      { name: "寒冰箭", cost: 2, count: 2, card_id: "CS2_024" },
      { name: "奥术智慧", cost: 3, count: 2, card_id: "CS2_023" },
      { name: "冰霜新星", cost: 3, count: 2, card_id: "CS2_026" },
      { name: "法术宝石", cost: 3, count: 2, card_id: "TOY_606" },
      { name: "聚合打击", cost: 4, count: 2, card_id: "TOY_603" },
      { name: "深渊之眼", cost: 4, count: 2, card_id: "WW_603" },
      { name: "暴风雪", cost: 6, count: 2, card_id: "CS2_028" },
      { name: "法力涌动", cost: 5, count: 2, card_id: "TOY_607" },
      { name: "烈焰风暴", cost: 7, count: 2, card_id: "CS2_032" },
      { name: "巨型法阵", cost: 8, count: 2, card_id: "WW_604" },
      { name: "深渊巨浪", cost: 9, count: 2, card_id: "TOY_608" },
      { name: "希芙", cost: 7, count: 1, card_id: "TTN_960" },
      { name: "约格-萨隆", cost: 10, count: 1, card_id: "TTN_841" },
      { name: "大法师安东尼达斯", cost: 7, count: 1, card_id: "EX1_559" },
      { name: "卡雷苟斯", cost: 9, count: 1, card_id: "DAL_609" },
      { name: "伊格尼斯", cost: 4, count: 1, card_id: "TTN_429" },
      { name: "彩虹画师", cost: 3, count: 1, card_id: "TOY_605" },
    ],
    matchups: { warrior: 48, mage: 50, hunter: 45, paladin: 56, priest: 55, rogue: 48, shaman: 50, warlock: 52, druid: 58, "demon-hunter": 48, "death-knight": 54 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 17, title: "过载萨满", title_en: "Overload Shaman", slug: "overload-shaman",
    hero_class: "shaman", archetype: "aggro", deck_code: "AAECAaoIAA+BBPkD/gWyBuAGsQjCCJMJ8+cC7/cClO8C4vgCi4UD",
    dust_cost: 5400, tier: 2, win_rate: 53.4,
    guide: "## 卡组思路\n\n利用过载法术打出超额法力曲线的强力节奏。前期用过载法术和随从快速抢血，配合解锁过载效果保持节奏。\n\n## 留牌策略\n\n- 闪电箭必留\n- 图腾魔像对所有对局留\n- 熔岩爆裂对慢速留\n\n## 关键回合\n\n- **1-2费**：过载法术抢节奏\n- **3费**：熔岩喷涌铺场\n- **5费**：嗜血收割",
    card_list: [
      { name: "闪电箭", cost: 1, count: 2, card_id: "EX1_238" },
      { name: "图腾魔像", cost: 1, count: 2, card_id: "TOY_707" },
      { name: "雷鸣要塞", cost: 1, count: 2, card_id: "WW_707" },
      { name: "熔岩爆裂", cost: 2, count: 2, card_id: "EX1_241" },
      { name: "图腾之力", cost: 2, count: 2, card_id: "WW_708" },
      { name: "过载领主", cost: 2, count: 2, card_id: "TOY_708" },
      { name: "闪电风暴", cost: 3, count: 2, card_id: "EX1_259" },
      { name: "熔岩喷涌", cost: 3, count: 2, card_id: "WW_709" },
      { name: "地下洪流", cost: 3, count: 2, card_id: "TOY_709" },
      { name: "妖术", cost: 4, count: 2, card_id: "EX1_246" },
      { name: "火元素", cost: 6, count: 2, card_id: "CS2_042" },
      { name: "嗜血", cost: 5, count: 2, card_id: "CS2_046" },
      { name: "风暴守卫", cost: 5, count: 2, card_id: "WW_710" },
      { name: "雷霆先锋", cost: 4, count: 2, card_id: "TOY_710" },
      { name: "布鲁坎", cost: 8, count: 1, card_id: "AV_258" },
      { name: "巨人猎手泰丽莎", cost: 6, count: 1, card_id: "WW_705" },
    ],
    matchups: { warrior: 50, mage: 55, hunter: 52, paladin: 48, priest: 54, rogue: 50, shaman: 50, warlock: 56, druid: 54, "demon-hunter": 52, "death-knight": 50 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 18, title: "铺场德鲁伊", title_en: "Token Druid", slug: "token-druid",
    hero_class: "druid", archetype: "aggro", deck_code: "AAECAZICBv0CxAbkCJTSApvoAo3wAgz9A+YF5gXkB+QI5Aj4qwKE5gKi5gL55QIA",
    dust_cost: 4800, tier: 2, win_rate: 53.0,
    guide: "## 卡组思路\n\n快速铺满场面，利用buff法术和嗜血效果一波斩杀。前期不断生成小随从，中期大buff终结。\n\n## 留牌策略\n\n- 激活、树人生长必留\n- 丛林之魂对所有对局留\n- 横扫对快攻留\n\n## 关键回合\n\n- **1-3费**：疯狂铺场\n- **4费**：丛林之魂buff全场\n- **5-6费**：森林之力+嗜血斩杀",
    card_list: [
      { name: "激活", cost: 0, count: 2, card_id: "EX1_169" },
      { name: "树人生长", cost: 1, count: 2, card_id: "TOY_804" },
      { name: "荆棘之心", cost: 1, count: 2, card_id: "WW_807" },
      { name: "扎根术", cost: 2, count: 2, card_id: "TOY_805" },
      { name: "丛林萌芽", cost: 2, count: 2, card_id: "WW_808" },
      { name: "力量印记", cost: 2, count: 2, card_id: "TOY_806" },
      { name: "丛林之魂", cost: 3, count: 2, card_id: "EX1_158" },
      { name: "蔓生根须", cost: 3, count: 2, card_id: "WW_809" },
      { name: "野蛮咆哮", cost: 3, count: 2, card_id: "CS2_011" },
      { name: "横扫", cost: 4, count: 2, card_id: "CS2_012" },
      { name: "灵魂铺展", cost: 4, count: 2, card_id: "TOY_807" },
      { name: "森林之力", cost: 5, count: 2, card_id: "EX1_571" },
      { name: "星火术", cost: 6, count: 2, card_id: "CS2_005" },
      { name: "树木种植", cost: 5, count: 2, card_id: "WW_810" },
      { name: "森林守护者", cost: 7, count: 1, card_id: "EX1_573" },
      { name: "暮阳菲叶", cost: 6, count: 1, card_id: "WW_806" },
    ],
    matchups: { warrior: 48, mage: 50, hunter: 52, paladin: 54, priest: 55, rogue: 48, shaman: 52, warlock: 50, druid: 50, "demon-hunter": 54, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 19, title: "鲜血死骑", title_en: "Blood Death Knight", slug: "blood-death-knight",
    hero_class: "death-knight", archetype: "control", deck_code: "AAECAdMKBuW1BJi8BOO+BJ3FBMrSBNzcBAz50ATZ1ATk4wTi6gSR8QTq9ATs9wTB+gSIjQXTkQXPkQXJngUA",
    dust_cost: 10800, tier: 2, win_rate: 52.4,
    guide: "## 卡组思路\n\n通过鲜血符文的强力治疗和吸血效果持续回复，利用亡语和尸体机制建立资源优势。后期靠大随从终结。\n\n## 留牌策略\n\n- 鲜血印记必留\n- 尸体消耗卡对所有对局留\n- 吸血法术对快攻留\n\n## 关键回合\n\n- **1-3费**：积累尸体资源\n- **4-5费**：鲜血增益触发\n- **7-10费**：终极大随从压制",
    card_list: [
      { name: "鲜血印记", cost: 1, count: 2, card_id: "MAW_020" },
      { name: "腐烂之握", cost: 1, count: 2, card_id: "WW_327" },
      { name: "骨骸矿工", cost: 1, count: 2, card_id: "TOY_340" },
      { name: "尸体收割者", cost: 2, count: 2, card_id: "MAW_021" },
      { name: "鲜血汲取", cost: 2, count: 2, card_id: "WW_328" },
      { name: "死亡之触", cost: 2, count: 2, card_id: "TOY_341" },
      { name: "骨骸巨兽", cost: 3, count: 2, card_id: "MAW_022" },
      { name: "亡者之镜", cost: 3, count: 2, card_id: "WW_329" },
      { name: "血色守卫", cost: 4, count: 2, card_id: "TOY_342" },
      { name: "暗影裂隙", cost: 4, count: 2, card_id: "MAW_023" },
      { name: "鲜血巨像", cost: 5, count: 2, card_id: "WW_330" },
      { name: "亡者复苏", cost: 6, count: 2, card_id: "TOY_343" },
      { name: "黑暗收割", cost: 7, count: 2, card_id: "MAW_024" },
      { name: "莫格莱尼", cost: 7, count: 1, card_id: "MAW_012" },
      { name: "巫妖王", cost: 10, count: 1, card_id: "MAW_013" },
      { name: "鲜血女王兰娜瑟尔", cost: 5, count: 1, card_id: "ICC_841" },
      { name: "亡骸伯爵里文戴尔", cost: 4, count: 1, card_id: "WW_331" },
    ],
    matchups: { warrior: 55, mage: 53, hunter: 48, paladin: 52, priest: 50, rogue: 50, shaman: 54, warlock: 48, druid: 52, "demon-hunter": 56, "death-knight": 50 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 20, title: "控制牧师", title_en: "Control Priest", slug: "control-priest",
    hero_class: "priest", archetype: "control", deck_code: "AAECAa0GBpibA5mbA6GhA8ChA7ahA+ehAwySBdMK1gqDlAO3rAPerAOfqQOFrQOIsQP",
    dust_cost: 11400, tier: 3, win_rate: 51.4,
    guide: "## 卡组思路\n\n极致的控制策略，通过大量治疗、偷牌和清场拖到后期。利用对手的资源反制对手，最终靠疲劳或大随从获胜。\n\n## 留牌策略\n\n- 真言术:盾必留\n- 暗言术:灭对大随从留\n- 灵魂鞭笞对快攻留\n\n## 关键回合\n\n- **1-3费**：治疗控场\n- **5-6费**：清场稳定\n- **8-10费**：大随从终结",
    card_list: [
      { name: "真言术:盾", cost: 0, count: 2, card_id: "CS2_004" },
      { name: "圣洁之光", cost: 1, count: 2, card_id: "CS1_130" },
      { name: "灵魂鞭笞", cost: 1, count: 2, card_id: "SCH_233" },
      { name: "暗言术:灭", cost: 3, count: 2, card_id: "EX1_622" },
      { name: "心灵之火", cost: 2, count: 2, card_id: "TOY_906" },
      { name: "命运编织", cost: 3, count: 2, card_id: "WW_909" },
      { name: "群体驱散", cost: 4, count: 2, card_id: "TOY_907" },
      { name: "暗影狂乱", cost: 4, count: 2, card_id: "WW_910" },
      { name: "圣光炸弹", cost: 5, count: 2, card_id: "GVG_009" },
      { name: "精神控制", cost: 8, count: 2, card_id: "CS1_113" },
      { name: "灵魂抽取", cost: 5, count: 2, card_id: "TOY_908" },
      { name: "圣疗术", cost: 6, count: 2, card_id: "EX1_354" },
      { name: "灵魂行者安都因", cost: 7, count: 1, card_id: "TOY_905" },
      { name: "穆罗兹翁德", cost: 8, count: 1, card_id: "WW_907" },
      { name: "扎利米", cost: 5, count: 1, card_id: "VAC_921" },
      { name: "亚煞极", cost: 7, count: 1, card_id: "WW_346" },
      { name: "约格-萨隆", cost: 10, count: 1, card_id: "TTN_841" },
      { name: "光芒女神", cost: 3, count: 1, card_id: "WW_911" },
    ],
    matchups: { warrior: 55, mage: 52, hunter: 44, paladin: 50, priest: 50, rogue: 48, shaman: 50, warlock: 52, druid: 54, "demon-hunter": 48, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 21, title: "快攻恶魔猎手", title_en: "Aggro Demon Hunter", slug: "aggro-demon-hunter",
    hero_class: "demon-hunter", archetype: "aggro", deck_code: "AAECAea5AwKN9wPHsgQO2cYD3dMDieQDiuQDjOQDi+gD8+gDwvEDifcDyIAE1JIEkp0E",
    dust_cost: 5000, tier: 2, win_rate: 54.0,
    guide: "## 卡组思路\n\n利用恶魔猎手低费随从和武器快速打出大量伤害。英雄技能是核心输出来源之一，配合攻击增益效果。\n\n## 留牌策略\n\n- 所有1费随从必留\n- 二段跳必留\n- 混沌打击对所有对局留\n\n## 关键回合\n\n- **1-2费**：随从铺场\n- **3费**：武器配合攻击\n- **5-6费**：爆发斩杀",
    card_list: [
      { name: "二段跳", cost: 1, count: 2, card_id: "TOY_400" },
      { name: "战斗烙印", cost: 1, count: 2, card_id: "WW_408" },
      { name: "邪能追踪者", cost: 1, count: 2, card_id: "TOY_406" },
      { name: "混沌打击", cost: 2, count: 2, card_id: "BT_235" },
      { name: "邪能学徒", cost: 2, count: 2, card_id: "WW_402" },
      { name: "混乱一击", cost: 2, count: 2, card_id: "TOY_407" },
      { name: "战刃吉他", cost: 3, count: 2, card_id: "ETC_080" },
      { name: "眼棱", cost: 3, count: 2, card_id: "BT_352" },
      { name: "邪能之翼", cost: 3, count: 2, card_id: "WW_409" },
      { name: "深渊射手", cost: 4, count: 2, card_id: "TOY_408" },
      { name: "战刃风暴", cost: 4, count: 2, card_id: "WW_410" },
      { name: "怒视行者", cost: 5, count: 2, card_id: "TOY_409" },
      { name: "恶魔变身", cost: 5, count: 2, card_id: "WW_411" },
      { name: "混沌洪流", cost: 6, count: 2, card_id: "TOY_410" },
      { name: "卡尔萨斯·逐日者", cost: 7, count: 1, card_id: "WW_407" },
      { name: "伊利达雷之怒", cost: 6, count: 1, card_id: "WW_406" },
    ],
    matchups: { warrior: 52, mage: 56, hunter: 50, paladin: 48, priest: 56, rogue: 50, shaman: 52, warlock: 54, druid: 55, "demon-hunter": 50, "death-knight": 52 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
  {
    id: 22, title: "奥丁战士", title_en: "Odyn Warrior", slug: "odyn-warrior",
    hero_class: "warrior", archetype: "combo", deck_code: "AAECAQcEkdMDveMDl+8D4PYDDRywAp3wAvbsAr3xAo7tApztAv3yAuP0Atn+Ag==",
    dust_cost: 9800, tier: 2, win_rate: 53.6,
    guide: "## 卡组思路\n\n大量积攒护甲并通过奥丁将所有获得的护甲转化为伤害。前期防守积攒，奥丁登场后每次获得护甲都对对手造成等量伤害。\n\n## 留牌策略\n\n- 盾牌猛击、盾牌格挡必留\n- 铸甲师对所有对局留\n- 乱斗对铺场对局留\n\n## 关键回合\n\n- **1-3费**：积攒护甲\n- **5费**：乱斗清场\n- **8费**：奥丁登场，开始护甲转伤害",
    card_list: [
      { name: "斩杀", cost: 1, count: 2, card_id: "CS2_108" },
      { name: "盾牌猛击", cost: 1, count: 2, card_id: "EX1_410" },
      { name: "铸甲锻造", cost: 1, count: 2, card_id: "WW_347" },
      { name: "铸甲师", cost: 2, count: 2, card_id: "EX1_402" },
      { name: "猛击冲锋", cost: 2, count: 2, card_id: "TOY_346" },
      { name: "残忍打击", cost: 2, count: 2, card_id: "WW_348" },
      { name: "盾牌格挡", cost: 3, count: 2, card_id: "EX1_606" },
      { name: "重甲守卫", cost: 3, count: 2, card_id: "TOY_347" },
      { name: "护甲压制", cost: 3, count: 2, card_id: "WW_349" },
      { name: "乱斗", cost: 5, count: 2, card_id: "EX1_407" },
      { name: "严阵以待", cost: 4, count: 2, card_id: "TOY_342" },
      { name: "护甲工匠", cost: 5, count: 2, card_id: "WW_350" },
      { name: "巨盾卫士", cost: 7, count: 2, card_id: "TOY_345" },
      { name: "奥丁", cost: 8, count: 1, card_id: "TTN_960" },
      { name: "格罗玛什·地狱咆哮", cost: 8, count: 1, card_id: "EX1_414" },
      { name: "砰砰博士", cost: 7, count: 1, card_id: "GVG_110" },
      { name: "吉利克斯三千型", cost: 5, count: 1, card_id: "TOY_330" },
    ],
    matchups: { warrior: 50, mage: 52, hunter: 48, paladin: 55, priest: 56, rogue: 52, shaman: 50, warlock: 54, druid: 52, "demon-hunter": 55, "death-knight": 50 },
    published_at: "2026-05-01T00:00:00Z", created_at: "2026-05-01T00:00:00Z",
  },
];

function enrichWithCardIds(deck: Deck): Deck {
  const hasCardIds = deck.card_list?.some((c) => c.card_id);
  if (hasCardIds) return deck;

  const demo = DEMO_DECKS.find((d) => d.slug === deck.slug);
  if (!demo) return deck;

  return { ...deck, card_list: demo.card_list, guide: demo.guide };
}

export async function getAllDecks(): Promise<Deck[]> {
  if (!supabase) return DEMO_DECKS;
  try {
    const { data, error } = await supabase
      .from("decks")
      .select("*")
      .order("tier", { ascending: true });
    if (error || !data || data.length === 0) return DEMO_DECKS;
    return data.map(enrichWithCardIds);
  } catch {
    return DEMO_DECKS;
  }
}

export async function getDeckBySlug(slug: string): Promise<Deck | null> {
  if (!supabase) return DEMO_DECKS.find((d) => d.slug === slug) || null;
  try {
    const { data, error } = await supabase
      .from("decks")
      .select("*")
      .eq("slug", slug)
      .single();
    if (error || !data) return DEMO_DECKS.find((d) => d.slug === slug) || null;
    return enrichWithCardIds(data);
  } catch {
    return DEMO_DECKS.find((d) => d.slug === slug) || null;
  }
}

export async function getDecksByClass(heroClass: string): Promise<Deck[]> {
  const all = await getAllDecks();
  if (heroClass === "all") return all;
  return all.filter((d) => d.hero_class === heroClass);
}
