-- HearthGuide 数据库 Schema
-- 在 Supabase SQL Editor 中执行

-- 1. 修改现有 posts 表，添加字段
ALTER TABLE posts ADD COLUMN IF NOT EXISTS title_en TEXT DEFAULT '';
ALTER TABLE posts ADD COLUMN IF NOT EXISTS category TEXT DEFAULT 'general';

-- 2. 创建 decks 表
CREATE TABLE IF NOT EXISTS decks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  title_en TEXT DEFAULT '',
  slug TEXT NOT NULL UNIQUE,
  hero_class TEXT NOT NULL,
  archetype TEXT NOT NULL DEFAULT 'midrange',
  deck_code TEXT NOT NULL DEFAULT '',
  dust_cost INT DEFAULT 0,
  tier INT DEFAULT 3,
  win_rate DECIMAL(5,2) DEFAULT 50.00,
  guide TEXT DEFAULT '',
  card_list JSONB DEFAULT '[]'::jsonb,
  matchups JSONB DEFAULT '{}'::jsonb,
  published_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- 3. RLS 策略
ALTER TABLE decks ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Decks are publicly readable"
  ON decks FOR SELECT USING (true);

CREATE POLICY "Authenticated users can insert decks"
  ON decks FOR INSERT WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can update decks"
  ON decks FOR UPDATE USING (auth.role() = 'authenticated');

CREATE POLICY "Authenticated users can delete decks"
  ON decks FOR DELETE USING (auth.role() = 'authenticated');

-- 4. 示例卡组数据
INSERT INTO decks (title, title_en, slug, hero_class, archetype, deck_code, dust_cost, tier, win_rate, guide, card_list, matchups) VALUES
(
  '海盗快攻战',
  'Pirate Aggro Warrior',
  'pirate-aggro-warrior',
  'warrior',
  'aggro',
  'AAECAQcGvAOvBJEG1Af/B5AQDJkB/wOOBe4G+wyIsAKbywKW6AKb8wIA',
  4800,
  1,
  56.2,
  '## 卡组思路

这是一套以海盗为核心的快攻战士卡组，利用低费随从快速抢血。

## 留牌策略

### 必留
- 所有1费随从
- 南海船长（配合武器）

### 后手额外留
- 血帆袭击者（有武器时）

## 对阵要点

- **对快攻**：抢节奏，不要换，冲脸
- **对控制**：尽量在前5回合打出足够伤害
- **对中速**：看手牌决定是否换随从',
  '[{"name":"恩佐斯的副官","cost":1,"count":2},{"name":"南海船长","cost":1,"count":2},{"name":"升级","cost":1,"count":2},{"name":"血帆袭击者","cost":2,"count":2},{"name":"英勇打击","cost":2,"count":2},{"name":"血帆火枪手","cost":3,"count":2},{"name":"暴乱狂战士","cost":3,"count":2},{"name":"吵吵机器人","cost":4,"count":2}]',
  '{"hunter":55,"mage":48,"paladin":60,"priest":62,"rogue":52,"shaman":58,"warlock":54,"warrior":45,"druid":57}'
),
(
  '冰冻法师',
  'Freeze Mage',
  'freeze-mage',
  'mage',
  'combo',
  'AAECAf0EBHHE+wKWBQ7AAawBnALJA6sE5gSWBewFiQ+ECM7vAgA=',
  8200,
  2,
  53.8,
  '## 卡组思路

经典的冰冻法师，通过拖延游戏到后期，利用法术爆发一波带走对手。

## 核心组合技

1. 大法师安东尼达斯 + 低费法术 = 无限火球
2. 寒冰屏障 + 末日 = 续命清场
3. 冰枪术 × 2 + 寒冰箭 × 2 + 火球术 × 2 = 34点爆发

## 留牌策略

- **必留**：工程师学徒、寒冰屏障、奥术智慧
- **对快攻额外留**：末日术、暴风雪',
  '[{"name":"奥术智慧","cost":3,"count":2},{"name":"寒冰屏障","cost":3,"count":2},{"name":"暴风雪","cost":6,"count":2},{"name":"火球术","cost":4,"count":2},{"name":"寒冰箭","cost":2,"count":2},{"name":"冰枪术","cost":1,"count":2},{"name":"末日术","cost":7,"count":2},{"name":"大法师安东尼达斯","cost":7,"count":1}]',
  '{"hunter":42,"mage":50,"paladin":55,"priest":60,"rogue":48,"shaman":45,"warlock":58,"warrior":35,"druid":52}'
),
(
  '奶骑',
  'Control Paladin',
  'control-paladin',
  'paladin',
  'control',
  'AAECAZ8FCIoB+gHcA/QFzwb6Bo8JucECBfsBpwW5BvYHjwkA',
  9600,
  2,
  54.1,
  '## 卡组思路

通过强力治疗和解场手段控制局面，后期依靠高质量随从取胜。

## 核心卡牌

- **提里奥·弗丁**：终极威胁
- **平等 + 奉献**：高效清场组合
- **圣疗术**：关键续命

## 对阵策略

- **对快攻**：前期苟活，4费后反击
- **对控制**：资源战，不要浪费关键牌
- **对OTK**：抢血压制，注意斩杀线',
  '[{"name":"平等","cost":2,"count":2},{"name":"奉献","cost":4,"count":2},{"name":"圣疗术","cost":6,"count":2},{"name":"力量祝福","cost":1,"count":2},{"name":"提里奥·弗丁","cost":8,"count":1},{"name":"公正之剑","cost":1,"count":2},{"name":"真银圣剑","cost":4,"count":2}]',
  '{"hunter":48,"mage":55,"paladin":50,"priest":45,"rogue":52,"shaman":56,"warlock":58,"warrior":60,"druid":53}'
);

-- 5. 更新 posts 示例数据的 category
UPDATE posts SET category = 'meta' WHERE slug = 'welcome';
UPDATE posts SET category = 'beginner' WHERE slug = 'supabase-backend';
UPDATE posts SET category = 'advanced' WHERE slug = 'cloudflare-protection';
